# -*- coding: utf-8 -*-
"""
Two more serialisations of the same content:

  graph/*.json     the definition graph in the node/edge shape the md files describe
  compiled/*.json  one resolved shape per FindingClass, references applied

The compiled form is what 00-stated-goals.md asks for: one concrete shape rather
than a general shape plus conditions an extractor has to evaluate. Conditional
content is resolved by emitting the defined subtypes as separate shapes.
"""
import json, os, re, datetime, collections
import snomed
import spec

TODAY = datetime.date.today().isoformat()
OUT = "/mnt/user-data/outputs/radcde-alpha"


def vb(status="proposed", n=1):
    return {"number": n, "status": status, "created": TODAY, "published": None,
            "last_modified": TODAY, "contributors": [
                {"id": "PERSON-000001", "role": "author", "via": "alpha-generator"}]}


def sct(code, label, match, primary=False):
    b = {"system": "SNOMEDCT", "code": code, "source_label": label, "match": match,
         "source_version": "supplied", "version": vb("published")}
    if primary:
        b["primary"] = True
    return b


def binding(system, code, label, match="exactMatch", primary=None):
    b = {"system": system, "code": code, "source_label": label, "match": match,
         "source_version": spec.RADLEX_VERSION, "version": vb("published")}
    if primary is not None:
        b["primary"] = primary
    return b


UNREIFIED = {"IS_A", "PART_OF", "CONTAINED_IN"}
_edge_seq = [0]


def E(edge, frm, to, props=None):
    """Every edge is an addressable object with an id and a version block, except
    the imported anatomy relations, which are regenerated by re-import and so have
    nothing durable to identify. Per objects/edges/01-edges.md."""
    e = {"edge": edge, "from": frm, "to": to, "props": props or {}}
    if edge not in UNREIFIED:
        _edge_seq[0] += 1
        e = {"node": "Edge", "id": f"EDGE-{_edge_seq[0]:06d}", **e, "version": vb()}
    return e


def refinements(anat, kind_rid):
    """Every concept below the declared kind that the anatomy module carries.

    The list is DERIVED, never authored: the class declares one kind and the build
    walks for it, so a new lobe or segment appearing upstream is picked up without
    anyone retyping a list.

    Both the sided and unsided forms are kept. RadLex carries `upper lobe of right
    lung` and `upper lobe of lung`, and a report may say either; a consumer wanting
    one form normalises, and the graph does not choose for it. Note that the walk
    goes down from the KIND rather than down from the scope target, because the
    unsided forms are general classes and are not part of any particular lung.
    """
    down = collections.defaultdict(list)
    for e in anat["is_a"] + anat["part_of"] + anat.get("local_edges", []):
        down[e["to"]].append(e["frm"])
    out, front = set(), [kind_rid]
    for _ in range(8):
        nxt = []
        for c in front:
            for k in down.get(c, []):
                if k not in out:
                    out.add(k); nxt.append(k)
        front = nxt
    return sorted(out)


def build():
    anat = json.load(open("anatomy.json"))
    nodes, edges = [], []

    # ---- anatomy
    al_by_key = {}
    for rid, nd in anat["nodes"].items():
        al_by_key[rid] = nd["al_id"]
        n = {"node": "AnatomicLocation", "id": nd["al_id"], "name": nd["name"],
             "definition": nd["definition"], "source": "imported",
             "synonyms": ([{"term": s, "type": "synonym"} for s in nd["synonyms"]] +
                          [{"term": s, "type": "acronym"} for s in nd.get("acronyms", [])]),
             "bindings": ([binding("RADLEX", rid, nd["source_label"], "exactMatch", True)]
                          + ([sct(*snomed.ANATOMY[rid])] if rid in snomed.ANATOMY else [])),
             "version": vb("published")}
        if nd.get("unsanctioned"):
            n["unsanctioned_terms"] = nd["unsanctioned"]
        if nd.get("misspellings"):
            n["misspellings"] = nd["misspellings"]
        if nd.get("concept_source"):
            n["concept_source"] = nd["concept_source"]
        if nd.get("has_real_definition"):
            n["definition_from_source"] = True
        if nd.get("replaced_by"):
            n["replaced_by"] = nd["replaced_by"]
        nodes.append(n)
    for lid, nd in anat["local_nodes"].items():
        al_by_key[lid] = nd["al_id"]
        n = {"node": "AnatomicLocation", "id": nd["al_id"], "name": nd["name"],
             "definition": nd["definition"], "source": "local",
             "source_status": nd["source_status"], "synonyms": [], "bindings": [],
             "version": vb()}
        if nd.get("request"):
            n["request"] = nd["request"]
        nodes.append(n)

    for e in anat["is_a"]:
        edges.append(E("IS_A", al_by_key[e["frm"]], al_by_key[e["to"]],
                       {"source": "imported", "system": "RADLEX",
                        "source_version": spec.RADLEX_VERSION}))
    for e in anat["part_of"]:
        edges.append(E("PART_OF", al_by_key[e["frm"]], al_by_key[e["to"]],
                       {"sense": e["prop"], "source": "imported", "system": "RADLEX",
                                "source_version": spec.RADLEX_VERSION}))
    for e in anat["local_edges"]:
        edges.append(E("PART_OF", al_by_key[e["frm"]], al_by_key[e["to"]],
                       {"sense": e["prop"], "source": "local",
                                "source_status": e["source_status"],
                                "request": e.get("request")}))

    # ---- data elements and values
    de_index, val_index = {}, {}
    for de in spec.DATA_ELEMENTS:
        de_index[de["id"]] = de
        n = {"node": "DataElement", "id": de["id"], "name": de["name"],
             "definition": de["definition"],
             "select_cardinality": "multi" if de.get("multi_select") else "single",
             "synonyms": [{"term": t, "type": ty} for t, ty in de.get("synonyms", [])],
             "bindings": ([binding("RADLEX", de["radlex"], de["name"], "closeMatch")]
                          if de.get("radlex") else []),
             "version": vb()}
        nodes.append(n)
        ordered = all(v[4] is not None for v in de["values"])
        for rid in de.get("scoped_to", []):
            edges.append(E("SCOPED_TO", de["id"], al_by_key[rid],
                           {"kind": "region", "strength": "required"}))
        for mcode in de.get("modality", []):
            edges.append(E("SEEN_ON", de["id"], mcode, {}))
        for vid, vname, vrid, vdef, vrank in de["values"]:
            val_index[vid] = (vname, de["id"])
            vn = {"node": "Value", "id": vid, "name": vname, "value": vname,
                  "definition": vdef, "synonyms": [],
                  "bindings": (([binding("RADLEX", vrid,
                                         spec.LOOSE_VALUE_MATCHES[vid][2]
                                         if vid in spec.LOOSE_VALUE_MATCHES else vname,
                                         spec.LOOSE_VALUE_MATCHES[vid][1]
                                         if vid in spec.LOOSE_VALUE_MATCHES else "exactMatch")]
                                if vrid else [])
                               + ([sct(*snomed.VALUES[vid])] if vid in snomed.VALUES else [])),
                  "version": vb()}
            if not vrid:
                vn["source"] = "local"
                vn["source_status"] = "unrequested"
            nodes.append(vn)
            props = {"rank": vrank} if ordered else {}
            if de.get("exclusive_none") == vid:
                props["exclusive"] = True
                props["exclusive_note"] = ("selecting this excludes every other value of "
                                           "this element")
            edges.append(E("HAS_VALUE", de["id"], vid, props))

    # ---- measurements
    for ms in spec.MEASUREMENTS:
        nodes.append({"node": "Measurement", "id": ms["id"], "name": ms["name"],
                      "definition": ms["definition"], "quantity_kind": ms["quantity_kind"],
                      "permitted_units": ms["permitted_units"], "method": ms["method"],
                      "synonyms": [], "bindings": [], "version": vb()})
        for c in ms.get("components", []):
            edges.append(E("HAS_MEASUREMENT_COMPONENT", ms["id"], c, {}))
        for d in ms.get("derived_from", []):
            edges.append(E("DERIVED_FROM_MEASUREMENT", ms["id"], d, {}))
        # A descriptor of a normal structure carries its own anatomic scope and
        # belongs to no finding. This was emitted to the OWL but not to the graph
        # until the evaluator found the measurement orphaned.
        if ms.get("scoped_to_anatomy"):
            edges.append(E("SCOPED_TO", ms["id"], al_by_key[ms["scope_target"]],
                           {"kind": "class", "strength": "required"}))

    # ---- assessment schemes
    as_index = {}
    for a in spec.ASSESSMENT_SCHEMES:
        as_index[a["id"]] = a
        nodes.append({"node": "AssessmentScheme", "id": a["id"], "name": a["name"],
                      "issuing_authority": a["authority"], "scheme_version": a["scheme_version"],
                      "scheme_scope": a["scope"],
                      "categories": [{"name": c[0], "rank": c[2],
                                      "bindings": ([binding("RADLEX", c[1], c[0])] if c[1] else [])}
                                     for c in a["categories"]],
                      "bindings": ([binding("RADLEX", a["radlex"], a["name"], "exactMatch", True)]
                                   if a.get("radlex") else []),
                      "version": vb()})

    for sid, cls, name, defn in spec.SCOPE_RESOLUTION:
        nodes.append({"node": "ScopeResolution", "id": sid, "name": name,
                      "definition": defn, "bindings": [], "version": vb()})

    for eid, cls, name, rid, defn in spec.ETIOLOGIES:
        nodes.append({"node": "Etiology", "id": eid, "name": name, "definition": defn,
                      "anchor_verdict": ("anchored" if rid else "unanchored_requestable"),
                      "bindings": (([binding("RADLEX", rid, name, "closeMatch", True)]
                                    if rid else [])
                                   + ([sct(*snomed.ETIOLOGY[eid])] if eid in snomed.ETIOLOGY else [])),
                      "version": vb()})

    for mid, code, label, rid in spec.MODALITIES:
        nodes.append({"node": "Modality", "id": mid, "name": code, "definition": label,
                      "bindings": ([binding("RADLEX", rid, label, "exactMatch", True)]
                                   + ([sct(*snomed.MODALITY[mid])] if mid in snomed.MODALITY else [])),
                      "version": vb("published")})
    for sid, short, label in spec.SUBSPECIALTIES:
        nodes.append({"node": "Subspecialty", "id": sid, "name": short, "definition": label,
                      "bindings": [], "version": vb("published")})

    # ---- findings
    fc_id = {f["cls"]: f["id"] for f in spec.FINDING_CLASSES}
    dx_id = {d["cls"]: d["id"] for d in spec.DIAGNOSES}

    def al(x):
        return al_by_key[x]

    for fc in spec.FINDING_CLASSES:
        n = {"node": "FindingClass", "id": fc["id"], "name": fc["name"],
             "definition": fc["definition"],
             "defined_concept": bool(fc.get("defined")),
             "synonyms": [{"term": t, "type": ty,
                           "scope": (fc.get("synonym_scope") or {}).get(t, "exact")}
                          for t, ty in fc.get("synonyms", [])],
             "bindings": (([binding("RADLEX", fc["radlex"], fc["name"],
                                    fc.get("match", "exactMatch"), True)]
                           if fc.get("radlex") else [])
                          + ([sct(*snomed.FINDINGS[fc["name"]])]
                             if fc["name"] in snomed.FINDINGS else [])),
             "version": vb()}
        if not fc.get("radlex"):
            n["source"] = "local"
            n["source_status"] = fc.get("source_status", "unrequested")
        if fc.get("criterion"):
            n["criterion"] = fc["criterion"]
        n["anchor_verdict"] = fc.get("anchor_verdict", "anchored")
        if fc.get("anchor_base"):
            n["anchor_base"] = {"system": "RADLEX", "code": fc["anchor_base"][0],
                                "label": fc["anchor_base"][1]}
            n["anchor_modifiers"] = [{"system": "RADLEX", "code": c, "label": l}
                                     for c, l in fc.get("anchor_modifiers", [])]
        if fc.get("request"):
            n["request"] = fc["request"]
        if fc.get("component"):
            n["component"] = True
        nodes.append(n)

        if fc.get("parent"):
            edges.append(E("SUBTYPE_OF", fc["id"], fc_id[fc["parent"]],
                       {"inheritance": "strict"}))
        eff_el, eff_ms, eff_mod, prov = spec.expand(fc)
        for deid in eff_el:
            props = {}
            if deid in (fc.get("narrow") or {}):
                props["narrow"] = fc["narrow"][deid]
            if deid in (fc.get("modality_scoped") or {}):
                props["modality"] = fc["modality_scoped"][deid]
            edges.append(E("HAS_DATA_ELEMENT", fc["id"], deid, props))
        for deid, allowed in (fc.get("narrow") or {}).items():
            if deid not in eff_el:
                props = {"narrow": allowed}
                if deid in (fc.get("modality_scoped") or {}):
                    props["modality"] = fc["modality_scoped"][deid]
                e = E("HAS_DATA_ELEMENT", fc["id"], deid, props)
                e["_inherited_from"] = fc.get("parent")
                edges.append(e)
        for msid in eff_ms:
            edges.append(E("HAS_MEASUREMENT", fc["id"], msid,
                           ({"generated_from_pattern": prov[msid]} if msid in prov else {})))
        for asid in fc.get("assessed_by", []):
            edges.append(E("ASSESSED_BY", fc["id"], asid, {}))
        for m in eff_mod:
            edges.append(E("SEEN_ON", fc["id"], m,
                       {}))
        for s in fc.get("in_subspecialty", []):
            edges.append(E("IN_SUBSPECIALTY", fc["id"], s,
                       {}))
        # Symmetric: stored once. A consumer walking edges out of the target must read
        # the flag and traverse backwards; two stored edges would mean two ids for one
        # assertion, and retiring one would leave the other standing.
        for target in fc.get("occurs_with", []):
            edges.append(E("OCCURS_WITH", fc["id"], fc_id[target], {"symmetric": True}))
        for cname, strength in fc.get("components", []):
            edges.append(E("HAS_COMPONENT", fc["id"], fc_id[cname],
                       {"strength": strength, "direction": "required_on_whole"}))
        if fc.get("component_of"):
            edges.append(E("COMPONENT_OF", fc["id"], fc_id[fc["component_of"]],
                           {"direction": "necessary_on_component"}))
        for prop, vid in fc.get("fixed", []):
            edges.append(E("HAS_VALUE_CONSTRAINT", fc["id"], vid,
                           {"element": prop, "defining": False,
                            "note": "fixed by the class definition, not offered as an element"}))
        for prop, target in fc.get("differentia", []):
            if prop.startswith("scopedTo"):
                edges.append(E("SCOPED_TO", fc["id"], al(target),
                               {"kind": "region", "strength": "required", "defining": True}))
            else:
                edges.append(E("HAS_VALUE_CONSTRAINT", fc["id"], target,
                       {"element": prop, "defining": True}))
        for target, kind_rid, kind_label in fc.get("refine_to", []):
            for r in refinements(anat, kind_rid):
                if r in al_by_key:
                    edges.append(E("REFINES_SCOPE_TO", fc["id"], al_by_key[r],
                                   {"of_scope": al_by_key[target], "kind": kind_label,
                                    "derived": True}))
        for sc in fc.get("scoped_to", []):
            rid, kind, strength = sc[0], sc[1], sc[2]
            origin = sc[3] if len(sc) > 3 else "local"
            edges.append(E("SCOPED_TO", fc["id"], al(rid),
                       {"kind": kind, "strength": strength,
                                    "source": origin}))

    for cls, rid, kind, strength in spec.SCOPE_ASSERTIONS:
        edges.append(E("SCOPED_TO", fc_id[cls], al(rid),
                       {"kind": kind, "strength": strength}))

    dx_id_map = {d["cls"]: d["id"] for d in spec.DIAGNOSES}
    for dx in spec.DIAGNOSES:
        n = {"node": "Diagnosis", "id": dx["id"], "name": dx["name"],
             "definition": dx["definition"],
             "synonyms": [{"term": t, "type": ty} for t, ty in dx.get("synonyms", [])],
             "bindings": (([binding("RADLEX", dx["radlex"], dx.get("source_label", dx["name"]),
                                    dx.get("match", "exactMatch"), True)]
                           if dx.get("radlex") else [])
                          + ([sct(*snomed.DIAGNOSES[dx["name"]],
                                  primary=(dx["name"] in snomed.SNOMED_PRIMARY))]
                             if dx["name"] in snomed.DIAGNOSES else [])),
             "version": vb()}
        if not dx.get("radlex"):
            n["source"] = "local"
            n["source_status"] = dx.get("source_status", "unrequested")
            if dx.get("request"):
                n["request"] = dx["request"]
        if dx.get("synonym_only_hit"):
            n["anchor_found_via"] = "synonym"
        n["anchor_verdict"] = dx.get("anchor_verdict", "anchored")
        if dx.get("anchor_base"):
            n["anchor_base"] = {"system": "RADLEX", "code": dx["anchor_base"][0],
                                "label": dx["anchor_base"][1]}
            n["anchor_modifiers"] = [{"system": "RADLEX", "code": c, "label": l}
                                     for c, l in dx.get("anchor_modifiers", [])]
        if dx.get("no_imaging_elements"):
            n["no_imaging_elements"] = True
        nodes.append(n)

        # evidential: the diagnosis can show itself as the target
        for target, typicality, specificity in dx.get("manifests_as", []):
            tid = fc_id.get(target) or dx_id_map.get(target)
            edges.append(E("MAY_MANIFEST_AS", dx["id"], tid,
                           {"typicality": typicality, "specificity": specificity,
                            "reading": "evidential", "inference_bearing": False}))
        # causal: the source can produce the target as a distinct second entity
        for target, typicality in dx.get("causes", []):
            tid = fc_id.get(target) or dx_id_map.get(target)
            edges.append(E("MAY_CAUSE", dx["id"], tid, {"typicality": typicality}))
        for target in dx.get("progresses_to", []):
            edges.append(E("MAY_PROGRESS_TO", dx["id"], dx_id_map[target], {}))
        for target in dx.get("occurs_with", []):
            edges.append(E("OCCURS_WITH", dx["id"], dx_id_map[target], {"symmetric": True}))
        for et in dx.get("etiology", []):
            edges.append(E("HAS_ETIOLOGY", dx["id"], et, {}))
        for sc in dx.get("scoped_to", []):
            rid, kind, strength = sc[0], sc[1], sc[2]
            edges.append(E("SCOPED_TO", dx["id"], al_by_key[rid],
                           {"kind": kind, "strength": strength}))
        for deid in dx.get("elements", []):
            edges.append(E("HAS_DATA_ELEMENT", dx["id"], deid,
                       {}))
        for asid in dx.get("assessed_by", []):
            edges.append(E("ASSESSED_BY", dx["id"], asid,
                       {}))

    facts = anat.get("imported_facts", {})
    for n in nodes:
        for b in n.get("bindings", []):
            f = facts.get(b.get("code"))
            if not f:
                continue
            if f.get("unsanctioned"):
                n["unsanctioned_terms"] = f["unsanctioned"]
            if f.get("concept_source"):
                n["concept_source"] = f["concept_source"]
            if f.get("source_definition"):
                n["source_definition"] = f["source_definition"][:300]
            if f.get("replaced_by"):
                n["replaced_by"] = f["replaced_by"]

    return nodes, edges, de_index, val_index, as_index, fc_id, dx_id, al_by_key


# --------------------------------------------------------------------------
def compile_findings(nodes, edges, de_index, as_index):
    """Resolve every reference into one flat shape per FindingClass.

    Inheritance is applied: a defined subtype carries everything its ancestors
    carry, so a consumer reads one shape and evaluates nothing.
    """
    byid = {n["id"]: n for n in nodes}

    def nm_of(i):
        return byid[i]["name"] if i in byid else i

    def code_of(i):
        for b in byid.get(i, {}).get("bindings", []):
            if b["system"] == "RADLEX":
                return b["code"]
        return None

    out_edges = collections.defaultdict(list)
    for e in edges:
        out_edges[e["from"]].append(e)

    parent = {e["from"]: e["to"] for e in edges if e["edge"] == "SUBTYPE_OF"}

    def chain(fid):
        c, seen = [fid], set()
        while c[-1] in parent and c[-1] not in seen:
            seen.add(c[-1])
            c.append(parent[c[-1]])
        return c

    compiled = []
    for n in nodes:
        if n["node"] != "FindingClass":
            continue
        anc = chain(n["id"])
        elements, measurements, schemes, scopes = {}, {}, [], []
        refines = {}
        modalities, subspecialties, components, represents = [], [], [], []
        caused_by, occurs_with, component_of, fixed_values = [], [], [], []
        narrowings = {}
        for fid in reversed(anc):                      # ancestors first
            for e in out_edges[fid]:
                if e["edge"] == "HAS_DATA_ELEMENT":
                    if "narrow" in e["props"]:
                        narrowings[e["to"]] = e["props"]["narrow"]
                    elements[e["to"]] = dict(
                        element_id=e["to"], inherited_from=(None if fid == n["id"] else fid),
                        modality=e["props"].get("modality"))
                elif e["edge"] == "HAS_MEASUREMENT":
                    measurements[e["to"]] = dict(
                        inherited_from=None if fid == n["id"] else fid,
)
                elif e["edge"] == "ASSESSED_BY":
                    schemes.append(e["to"])
                elif e["edge"] == "SEEN_ON":
                    modalities.append(e["to"])
                elif e["edge"] == "IN_SUBSPECIALTY":
                    subspecialties.append(e["to"])
                elif e["edge"] == "HAS_COMPONENT":
                    components.append(dict(finding=e["to"], strength=e["props"].get("strength")))
                elif e["edge"] == "SCOPED_TO":
                    scopes.append(dict(location=e["to"], **e["props"]))
                elif e["edge"] == "REFINES_SCOPE_TO":
                    refines.setdefault(e["props"]["of_scope"], []).append(e["to"])
                elif e["edge"] == "OCCURS_WITH":
                    occurs_with.append(e["to"])
                elif e["edge"] == "COMPONENT_OF":
                    component_of.append(e["to"])
                elif e["edge"] == "HAS_VALUE_CONSTRAINT":
                    fixed_values.append(dict(value_id=e["to"],
                                             element=e["props"].get("element"),
                                             defining=e["props"].get("defining", False)))
                elif e["edge"] in ("MAY_REPRESENT", "MAY_MANIFEST_AS"):
                    represents.append(e["to"])

        for e in edges:
            if e["edge"] in ("MAY_BE_REPRESENTED_BY", "MAY_MANIFEST_AS") and e["to"] in anc:
                represents.append(e["from"])
            if e["edge"] == "MAY_CAUSE" and e["to"] in anc:
                caused_by.append(e["from"])
            if e["edge"] == "OCCURS_WITH" and e["to"] in anc:
                occurs_with.append(e["from"])

        shape = dict(
            finding_id=n["id"], name=n["name"], definition=n["definition"],
            subtype_of=parent.get(n["id"]),
            defined_concept=n.get("defined_concept", False),
            bindings=n.get("bindings", []), synonyms=n.get("synonyms", []),
            anatomic_scope=[
                dict(s, name=nm_of(s["location"]),
                     **({"permitted_refinements":
                         [{"code": code_of(r), "name": nm_of(r), "id": r}
                          for r in sorted(refines[s["location"]], key=nm_of)]}
                        if s["location"] in refines else {}))
                for s in scopes],
            seen_on=sorted(set(modalities)),
            subspecialty=sorted(set(subspecialties)),
            elements=[], measurements=[], assessment_schemes=[],
            components=components,
            may_represent=sorted(set(represents)),
            may_be_caused_by=sorted(set(caused_by)),
            occurs_with=sorted(set(occurs_with)),
            component_of=(component_of[0] if component_of else None),
            component=bool(n.get("component")),
            fixed_values=fixed_values,
            anchor_verdict=n.get("anchor_verdict", "anchored"),
            anchor_base=n.get("anchor_base"),
            anchor_modifiers=n.get("anchor_modifiers", []),
            change_request=n.get("request"),
            source_definition=n.get("source_definition"),
            concept_source=n.get("concept_source"),
            version=n["version"])
        if n.get("criterion"):
            shape["criterion"] = n["criterion"]
        if n.get("source_status"):
            shape["source"] = "local"
            shape["source_status"] = n["source_status"]

        for eid, meta in elements.items():
            de = de_index[eid]
            allowed = narrowings.get(eid)
            vals = [v for v in de["values"] if allowed is None or v[0] in allowed]
            ordered = all(v[4] is not None for v in de["values"])
            shape["elements"].append(dict(
                element_id=eid, name=de["name"], definition=de["definition"],
                select_cardinality="multi" if de.get("multi_select") else "single",
                narrowed=allowed is not None,
                modality_restricted_to=meta["modality"],
                inherited_from=meta["inherited_from"],
                permitted_values=[dict(
                    value_id=v[0], name=v[1], definition=v[3],
                    rank=(v[4] if ordered else None),
                    **({"exclusive": True,
                        "exclusive_note": "selecting this excludes every other value of "
                                          "this element"}
                       if de.get("exclusive_none") == v[0] else {}),
                    bindings=([binding("RADLEX", v[2], v[1])] if v[2] else []))
                    for v in vals]))
        for mid, meta in measurements.items():
            ms = next(m for m in spec.MEASUREMENTS if m["id"] == mid)
            shape["measurements"].append(dict(
                measurement_id=mid, name=ms["name"], definition=ms["definition"],
                quantity_kind=ms["quantity_kind"], permitted_units=ms["permitted_units"],
                method=ms["method"], inherited_from=meta["inherited_from"],
                components=ms.get("components", [])))
        for sid in sorted(set(schemes)):
            a = as_index[sid]
            shape["assessment_schemes"].append(dict(
                scheme_id=sid, name=a["name"], issuing_authority=a["authority"],
                scheme_version=a["scheme_version"], scope=a["scope"],
                categories=[dict(name=c[0], rank=c[2]) for c in a["categories"]]))
        compiled.append(shape)
    return compiled


if __name__ == "__main__":
    os.makedirs(f"{OUT}/graph", exist_ok=True)
    os.makedirs(f"{OUT}/compiled", exist_ok=True)
    nodes, edges, de_index, val_index, as_index, fc_id, dx_id, al_by_key = build()

    by_type = collections.Counter(n["node"] for n in nodes)
    by_edge = collections.Counter(e["edge"] for e in edges)

    json.dump({"nodes": nodes, "edges": edges,
               "stats": {"nodes_by_type": dict(by_type), "edges_by_type": dict(by_edge),
                         "total_nodes": len(nodes), "total_edges": len(edges)}},
              open(f"{OUT}/graph/definition-graph.json", "w"), indent=1)

    compiled = compile_findings(nodes, edges, de_index, as_index)
    for c in compiled:
        json.dump(c, open(f"{OUT}/compiled/{c['finding_id']}-{c['name'].replace(' ', '-')}.json", "w"),
                  indent=1)
    json.dump(compiled, open(f"{OUT}/compiled/_all-findings.json", "w"), indent=1)

    comp = {f["cls"] for f in spec.FINDING_CLASSES if f.get("component")}
    standalone = [c for c in compiled if c["name"] not in
                  {f["name"] for f in spec.FINDING_CLASSES if f.get("component")}]
    components = [c for c in compiled if c not in standalone]
    json.dump({
        "value_set": "finding-classes",
        "description": ("Every FindingClass is anatomically anchored and may be emitted as an "
                        "answer, except components, which are reached only through "
                        "HAS_COMPONENT. Authoring patterns are not nodes, name no elements, "
                        "and appear in no artifact."),
        "source_version": spec.RADLEX_VERSION,
        "standalone": [{"finding_id": c["finding_id"], "name": c["name"]} for c in standalone],
        "component_only": [{"finding_id": c["finding_id"], "name": c["name"]}
                           for c in components],

        "counts": {"standalone": len(standalone), "component_only": len(components),
                   "patterns": "not in any artifact"},
    }, open(f"{OUT}/compiled/_value-set-findings.json", "w"), indent=1)

    lint_out = spec.lint()
    json.dump({"rules": spec.PATTERN_LINT, "findings": lint_out, "clean": not lint_out,
               "note": "Authoring checks. Advisory: none is enforced by a reasoner and none "
                       "constrains what an author may write."},
              open(f"{OUT}/compiled/_authoring-lint.json", "w"), indent=1)
    print(f"\nvalue set: {len(standalone)} standalone, {len(components)} component-only, "
          f"{len(spec.PATTERNS)} patterns withheld from the graph")
    print(f"pattern lint: {'clean' if not lint_out else str(len(lint_out)) + ' findings'}")

    # duplication cost of the no-value-sharing rule
    from collections import defaultdict
    by_name = defaultdict(list)
    for n in nodes:
        if n["node"] == "Value":
            by_name[n["name"].lower()].append(n["id"])
    dupes = {k: v for k, v in by_name.items() if len(v) > 1}

    print("nodes by type:", dict(by_type))
    print("edges by type:", dict(by_edge))
    print(f"\ncompiled shapes: {len(compiled)}")
    for c in sorted(compiled, key=lambda x: -len(x["elements"])):
        inh = sum(1 for e in c["elements"] if e["inherited_from"] or e.get("from_pattern"))
        print(f"  {c['name']:42s} elements={len(c['elements']):2d} "
              f"(inherited {inh}) values="
              f"{sum(len(e['permitted_values']) for e in c['elements']):3d} "
              f"measurements={len(c['measurements'])}")
    print(f"\nvalue nodes: {by_type['Value']}; "
          f"duplicated labels under the no-sharing rule: {len(dupes)} -> "
          f"{ {k: len(v) for k, v in dupes.items()} }")
