# -*- coding: utf-8 -*-
"""
Merged single-file builds.

The two-module form (alpha + anatomy, wired by catalog-v001.xml) is the right
shape for real work: the anatomy module is regenerated by re-import and the
authored layer is not. But it has a failure mode, which is that if the catalog
is not found, Protege tries to fetch the import over the network and the
ontology silently comes up empty.

These merged files have no owl:imports at all. One file, nothing to resolve.
Use them to get started; move to the modular form once that is working.
"""
import os
from rdflib import Graph, URIRef, Literal
from rdflib.namespace import RDF, RDFS, OWL, DCTERMS

OUT = "/mnt/user-data/outputs/radcde-alpha"
BASE = "https://radelement.org/ng/"


def merge(parts, iri, title, comment):
    g = Graph()
    for p, fmt in parts:
        g.parse(p, format=fmt)
    # drop every ontology header and import, then write one clean header
    for s in list(g.subjects(RDF.type, OWL.Ontology)):
        for p_, o_ in list(g.predicate_objects(s)):
            g.remove((s, p_, o_))
    ont = URIRef(iri)
    g.add((ont, RDF.type, OWL.Ontology))
    g.add((ont, DCTERMS.title, Literal(title)))
    g.add((ont, OWL.versionInfo, Literal("alpha-0.1")))
    g.add((ont, RDFS.comment, Literal(comment)))
    assert len(list(g.triples((None, OWL.imports, None)))) == 0
    return g


if __name__ == "__main__":
    ttl = [(f"{OUT}/radcde-anatomy.ttl", "turtle"), (f"{OUT}/radcde-alpha.ttl", "turtle")]

    g1 = merge(ttl, BASE + "radcde-standalone",
               "RadElement next-gen alpha (single file, no imports)",
               "Authored definition layer and imported anatomy merged into one file. "
               "No owl:imports and no catalog needed. Equivalent in content to "
               "radcde-alpha.ttl plus radcde-anatomy.ttl.")
    g1.serialize(f"{OUT}/standalone/radcde-standalone.ttl", format="turtle")
    g1.serialize(f"{OUT}/standalone/radcde-standalone.owl", format="xml")

    g2 = merge(ttl + [(f"{OUT}/radcde-probes.ttl", "turtle")],
               BASE + "radcde-standalone-probes",
               "RadElement next-gen alpha with probes (single file, no imports)",
               "As radcde-standalone, plus the ten deliberate probe classes. Run a "
               "reasoner: four Group B probes should appear under owl:Nothing, and "
               "B5 should not.")
    g2.serialize(f"{OUT}/standalone/radcde-standalone-probes.ttl", format="turtle")
    g2.serialize(f"{OUT}/standalone/radcde-standalone-probes.owl", format="xml")

    for f in ["radcde-standalone.ttl", "radcde-standalone.owl",
              "radcde-standalone-probes.ttl", "radcde-standalone-probes.owl"]:
        p = f"{OUT}/standalone/{f}"
        fmt = "turtle" if f.endswith(".ttl") else "xml"
        gg = Graph().parse(p, format=fmt)
        n_ont = len(list(gg.subjects(RDF.type, OWL.Ontology)))
        n_imp = len(list(gg.triples((None, OWL.imports, None))))
        n_cls = len(set(gg.subjects(RDF.type, OWL.Class)))
        n_lbl = len(list(gg.triples((None, RDFS.label, None))))
        print(f"{f:34s} triples={len(gg):5d} classes={n_cls:4d} labels={n_lbl:4d} "
              f"ontology_headers={n_ont} imports={n_imp} "
              f"size={os.path.getsize(p)//1024}KB")
